// 该文件由 工具/i18n_build.py 生成，请勿手工编辑。
// 中文原文 → 英文词表；键是源码里的原始字面量内容（含 \n 一类的转义写法）。
#include "core/Loc.h"

#include <QHash>

namespace Loc
{
namespace
{

const QHash<QString, QString>& englishTable()
{
    static const QHash<QString, QString> table{
        {QStringLiteral("无"), QStringLiteral("None")},
        {QStringLiteral("空"), QStringLiteral("Empty")},
        {QStringLiteral("轴"), QStringLiteral("Axis")},
        {QStringLiteral("上移"), QStringLiteral("Move up")},
        {QStringLiteral("下移"), QStringLiteral("Move down")},
        {QStringLiteral("依据"), QStringLiteral("Evidence")},
        {QStringLiteral("保存"), QStringLiteral("Save")},
        {QStringLiteral("关闭"), QStringLiteral("Close")},
        {QStringLiteral("初始"), QStringLiteral("initial")},
        {QStringLiteral("删除"), QStringLiteral("Delete")},
        {QStringLiteral("单轴"), QStringLiteral("Single axis")},
        {QStringLiteral("反向"), QStringLiteral("Invert")},
        {QStringLiteral("取消"), QStringLiteral("Cancel")},
        {QStringLiteral("可用"), QStringLiteral("Ready")},
        {QStringLiteral("同名"), QStringLiteral("Same name")},
        {QStringLiteral("名↑"), QStringLiteral("Name↑")},
        {QStringLiteral("名↓"), QStringLiteral("Name↓")},
        {QStringLiteral("名称"), QStringLiteral("Name")},
        {QStringLiteral("启用"), QStringLiteral("Enable")},
        {QStringLiteral("备注"), QStringLiteral("Note")},
        {QStringLiteral("复位"), QStringLiteral("Reset")},
        {QStringLiteral("多轴"), QStringLiteral("Multi-axis")},
        {QStringLiteral("失效"), QStringLiteral("Missing")},
        {QStringLiteral("帮助"), QStringLiteral("Help")},
        {QStringLiteral("快速"), QStringLiteral("Fast")},
        {QStringLiteral("急停"), QStringLiteral("Panic stop")},
        {QStringLiteral("排序"), QStringLiteral("Sort")},
        {QStringLiteral("描述"), QStringLiteral("Description")},
        {QStringLiteral("播放"), QStringLiteral("Play")},
        {QStringLiteral("文件"), QStringLiteral("File")},
        {QStringLiteral("新↑"), QStringLiteral("New↑")},
        {QStringLiteral("新↓"), QStringLiteral("New↓")},
        {QStringLiteral("新建"), QStringLiteral("New")},
        {QStringLiteral("日↑"), QStringLiteral("Date↑")},
        {QStringLiteral("日↓"), QStringLiteral("Date↓")},
        {QStringLiteral("时↑"), QStringLiteral("Hr↑")},
        {QStringLiteral("时↓"), QStringLiteral("Hr↓")},
        {QStringLiteral("更多"), QStringLiteral("More")},
        {QStringLiteral("最前"), QStringLiteral("first")},
        {QStringLiteral("最后"), QStringLiteral("last")},
        {QStringLiteral("未知"), QStringLiteral("Unknown")},
        {QStringLiteral("标准"), QStringLiteral("Standard")},
        {QStringLiteral("标签"), QStringLiteral("Tags")},
        {QStringLiteral("标题"), QStringLiteral("Title")},
        {QStringLiteral("添加"), QStringLiteral("Add")},
        {QStringLiteral("状态"), QStringLiteral("Status")},
        {QStringLiteral("稍后"), QStringLiteral("Later")},
        {QStringLiteral("端口"), QStringLiteral("Port")},
        {QStringLiteral("视图"), QStringLiteral("View")},
        {QStringLiteral("设置"), QStringLiteral("Settings")},
        {QStringLiteral("语言"), QStringLiteral("Language")},
        {QStringLiteral("连接"), QStringLiteral("Connect")},
        {QStringLiteral("连播"), QStringLiteral("Auto-next")},
        {QStringLiteral("退出"), QStringLiteral("Exit")},
        {QStringLiteral("配置"), QStringLiteral("Profiles")},
        {QStringLiteral("长↑"), QStringLiteral("Len↑")},
        {QStringLiteral("长↓"), QStringLiteral("Len↓")},
        {QStringLiteral("音量"), QStringLiteral("Volume")},
        {QStringLiteral("默认"), QStringLiteral("Default")},
        {QStringLiteral(" 副本"), QStringLiteral(" copy")},
        {QStringLiteral("不可用"), QStringLiteral("Unavailable")},
        {QStringLiteral("全屏中"), QStringLiteral("in full screen")},
        {QStringLiteral("另存为"), QStringLiteral("Save as")},
        {QStringLiteral("同大小"), QStringLiteral("Same size")},
        {QStringLiteral("同时长"), QStringLiteral("Same duration")},
        {QStringLiteral("媒体库"), QStringLiteral("Media library")},
        {QStringLiteral("已取消"), QStringLiteral("Cancelled")},
        {QStringLiteral("循环中"), QStringLiteral("Looping")},
        {QStringLiteral("循环表"), QStringLiteral("loop table")},
        {QStringLiteral("收藏夹"), QStringLiteral("Collections")},
        {QStringLiteral("新名称"), QStringLiteral("New name")},
        {QStringLiteral("新建…"), QStringLiteral("New…")},
        {QStringLiteral("无标签"), QStringLiteral("Untagged")},
        {QStringLiteral("无脚本"), QStringLiteral("No script")},
        {QStringLiteral("时间段"), QStringLiteral("Time range")},
        {QStringLiteral("未保存"), QStringLiteral("Unsaved")},
        {QStringLiteral("未归类"), QStringLiteral("Ungrouped")},
        {QStringLiteral("未收藏"), QStringLiteral("Not in a collection")},
        {QStringLiteral("未知轴"), QStringLiteral("Unknown axis")},
        {QStringLiteral("浮层右"), QStringLiteral("overlay right")},
        {QStringLiteral("浮层左"), QStringLiteral("overlay left")},
        {QStringLiteral("获取中"), QStringLiteral("Pending")},
        {QStringLiteral("被占用"), QStringLiteral("In use")},
        {QStringLiteral("轴限制"), QStringLiteral("Axis limits")},
        {QStringLiteral(" 窗口="), QStringLiteral(" window=")},
        {QStringLiteral("# 全部"), QStringLiteral("# All")},
        {QStringLiteral("%1 个"), QStringLiteral("%1")},
        {QStringLiteral("%1 秒"), QStringLiteral("%1 s")},
        {QStringLiteral("%1 轴"), QStringLiteral("%1 axes")},
        {QStringLiteral("★ 全部"), QStringLiteral("★ All")},
        {QStringLiteral("串口错误"), QStringLiteral("Serial error")},
        {QStringLiteral("保存失败"), QStringLiteral("Save failed")},
        {QStringLiteral("全部标签"), QStringLiteral("All tags")},
        {QStringLiteral("全部片段"), QStringLiteral("All clips")},
        {QStringLiteral("全部视频"), QStringLiteral("All videos")},
        {QStringLiteral("删除失败"), QStringLiteral("Delete failed")},
        {QStringLiteral("删除标签"), QStringLiteral("Delete tag")},
        {QStringLiteral("删除配置"), QStringLiteral("Delete profile")},
        {QStringLiteral("单轴测试"), QStringLiteral("Single axis test")},
        {QStringLiteral("参数无效"), QStringLiteral("Invalid argument")},
        {QStringLiteral("另存为…"), QStringLiteral("Save as…")},
        {QStringLiteral("可以打开"), QStringLiteral("Can be opened")},
        {QStringLiteral("可选备注"), QStringLiteral("Optional note")},
        {QStringLiteral("合并脚本"), QStringLiteral("Merged script")},
        {QStringLiteral("启动失败"), QStringLiteral("Startup failed")},
        {QStringLiteral("回到中位"), QStringLiteral("Back to center")},
        {QStringLiteral("失效条目"), QStringLiteral("Missing entries")},
        {QStringLiteral("媒体信息"), QStringLiteral("Media info")},
        {QStringLiteral("字体大小"), QStringLiteral("Font size")},
        {QStringLiteral("导入失败"), QStringLiteral("Import failed")},
        {QStringLiteral("导入完成"), QStringLiteral("Import finished")},
        {QStringLiteral("导出失败"), QStringLiteral("Export failed")},
        {QStringLiteral("强制释放"), QStringLiteral("Force release")},
        {QStringLiteral("当前音量"), QStringLiteral("Current volume")},
        {QStringLiteral("循环列表"), QStringLiteral("Loop list")},
        {QStringLiteral("打开视频"), QStringLiteral("Open video")},
        {QStringLiteral("拆分多轴"), QStringLiteral("Split multi-axis")},
        {QStringLiteral("排序方式"), QStringLiteral("Sort by")},
        {QStringLiteral("操作失败"), QStringLiteral("Operation failed")},
        {QStringLiteral("新建失败"), QStringLiteral("Create failed")},
        {QStringLiteral("新建配置"), QStringLiteral("New profile")},
        {QStringLiteral("无法删除"), QStringLiteral("Cannot delete")},
        {QStringLiteral("最大位置"), QStringLiteral("Maximum position")},
        {QStringLiteral("最小位置"), QStringLiteral("Minimum position")},
        {QStringLiteral("未知端口"), QStringLiteral("Unknown port")},
        {QStringLiteral("标签名称"), QStringLiteral("Tag name")},
        {QStringLiteral("添加循环"), QStringLiteral("Add loop")},
        {QStringLiteral("清理完成"), QStringLiteral("Clean-up finished")},
        {QStringLiteral("清除标记"), QStringLiteral("Clear markers")},
        {QStringLiteral("界面语言"), QStringLiteral("Interface language")},
        {QStringLiteral("移除选中"), QStringLiteral("Remove selected")},
        {QStringLiteral("立即重启"), QStringLiteral("Restart now")},
        {QStringLiteral("终止播放"), QStringLiteral("Stop playback")},
        {QStringLiteral("脚本偏移"), QStringLiteral("Script offset")},
        {QStringLiteral("覆盖配置"), QStringLiteral("Overwrite profile")},
        {QStringLiteral("视频全屏"), QStringLiteral("Video full screen")},
        {QStringLiteral("视频片段"), QStringLiteral("Video clip")},
        {QStringLiteral("视频解码"), QStringLiteral("Video decoding")},
        {QStringLiteral("跳转安全"), QStringLiteral("Seek safety")},
        {QStringLiteral("软件解码"), QStringLiteral("Software decoding")},
        {QStringLiteral("轴限制…"), QStringLiteral("Axis limits…")},
        {QStringLiteral("配置名称"), QStringLiteral("Profile name")},
        {QStringLiteral("重命名…"), QStringLiteral("Rename…")},
        {QStringLiteral("重新关联"), QStringLiteral("Relink")},
        {QStringLiteral("重新扫描"), QStringLiteral("Rescan")},
        {QStringLiteral("驱动异常"), QStringLiteral("Driver problem")},
        {QStringLiteral("默认脚本"), QStringLiteral("Default script")},
        {QStringLiteral("# 无标签"), QStringLiteral("# Untagged")},
        {QStringLiteral("] 全屏="), QStringLiteral("] fullScreen=")},
        {QStringLiteral("★ 未归类"), QStringLiteral("★ Ungrouped")},
        {QStringLiteral("★ 未收藏"), QStringLiteral("★ Not collected")},
        {QStringLiteral("中位/归位"), QStringLiteral("Center / home")},
        {QStringLiteral("主轴 L0"), QStringLiteral("Stroke L0")},
        {QStringLiteral("俯仰 R2"), QStringLiteral("Pitch R2")},
        {QStringLiteral("删除收藏夹"), QStringLiteral("Delete collection")},
        {QStringLiteral("删除片段…"), QStringLiteral("Delete clip…")},
        {QStringLiteral("刷新媒体库"), QStringLiteral("Refresh media library")},
        {QStringLiteral("前后 L1"), QStringLiteral("Surge L1")},
        {QStringLiteral("右边缘上部"), QStringLiteral("right edge, upper")},
        {QStringLiteral("同修改时间"), QStringLiteral("Same modified time")},
        {QStringLiteral("同步 --"), QStringLiteral("Sync --")},
        {QStringLiteral("名称已存在"), QStringLiteral("Name already exists")},
        {QStringLiteral("吸吮 A1"), QStringLiteral("Suck A1")},
        {QStringLiteral("备注：%1"), QStringLiteral("Note: %1")},
        {QStringLiteral("媒体信息…"), QStringLiteral("Media info…")},
        {QStringLiteral("媒体库管理"), QStringLiteral("Media library manager")},
        {QStringLiteral("导入配置…"), QStringLiteral("Import profiles…")},
        {QStringLiteral("导出配置…"), QStringLiteral("Export profiles…")},
        {QStringLiteral("展开媒体库"), QStringLiteral("Expand media library")},
        {QStringLiteral("左右 L2"), QStringLiteral("Sway L2")},
        {QStringLiteral("左边缘上部"), QStringLiteral("left edge, upper")},
        {QStringLiteral("已新建配置"), QStringLiteral("Profile created")},
        {QStringLiteral("已迁移%1"), QStringLiteral("Moved %1")},
        {QStringLiteral("循环收藏夹"), QStringLiteral("Loop collections")},
        {QStringLiteral("打开视频…"), QStringLiteral("Open video…")},
        {QStringLiteral("扭转 R0"), QStringLiteral("Twist R0")},
        {QStringLiteral("折叠媒体库"), QStringLiteral("Collapse media library")},
        {QStringLiteral("折叠探针["), QStringLiteral("Fold probe [")},
        {QStringLiteral("按标签筛选"), QStringLiteral("Filter by tag")},
        {QStringLiteral("收藏夹操作"), QStringLiteral("Collection actions")},
        {QStringLiteral("文件不存在"), QStringLiteral("File not found")},
        {QStringLiteral("新建收藏夹"), QStringLiteral("New collection")},
        {QStringLiteral("新配置名称"), QStringLiteral("New profile name")},
        {QStringLiteral("显示媒体库"), QStringLiteral("Show media library")},
        {QStringLiteral("显示热力图"), QStringLiteral("Show heat map")},
        {QStringLiteral("标签不存在"), QStringLiteral("Tag not found")},
        {QStringLiteral("标签：%1"), QStringLiteral("Tags: %1")},
        {QStringLiteral("测试 0%"), QStringLiteral("Test 0%")},
        {QStringLiteral("润滑 A2"), QStringLiteral("Lube A2")},
        {QStringLiteral("清理失效项"), QStringLiteral("Clean up missing entries")},
        {QStringLiteral("管理标签…"), QStringLiteral("Manage tags…")},
        {QStringLiteral("编辑信息…"), QStringLiteral("Edit info…")},
        {QStringLiteral("缩略图大小"), QStringLiteral("Thumbnail size")},
        {QStringLiteral("翻滚 R1"), QStringLiteral("Roll R1")},
        {QStringLiteral("脚本未加载"), QStringLiteral("No script loaded")},
        {QStringLiteral("设备已断开"), QStringLiteral("Device disconnected")},
        {QStringLiteral("设备未连接"), QStringLiteral("No device")},
        {QStringLiteral("跳转安全…"), QStringLiteral("Seek safety…")},
        {QStringLiteral("选择脚本…"), QStringLiteral("Choose script…")},
        {QStringLiteral("配置 %1"), QStringLiteral("Profile %1")},
        {QStringLiteral("配置档管理"), QStringLiteral("Manage profiles")},
        {QStringLiteral("重命名失败"), QStringLiteral("Rename failed")},
        {QStringLiteral("重命名标签"), QStringLiteral("Rename tag")},
        {QStringLiteral("重命名配置"), QStringLiteral("Rename profile")},
        {QStringLiteral("重新关联到"), QStringLiteral("Relink to")},
        {QStringLiteral("震动 V0"), QStringLiteral("Vibe V0")},
        {QStringLiteral(" 记住折叠="), QStringLiteral(" rememberedCollapsed=")},
        {QStringLiteral("%1 已连接"), QStringLiteral("%1 connected")},
        {QStringLiteral("%1 轴文件"), QStringLiteral("%1 axis file")},
        {QStringLiteral("仅显示有脚本"), QStringLiteral("Only videos with a script")},
        {QStringLiteral("从收藏夹移除"), QStringLiteral("Remove from collection")},
        {QStringLiteral("优先硬件解码"), QStringLiteral("Prefer hardware decoding")},
        {QStringLiteral("删除循环片段"), QStringLiteral("Delete loop clip")},
        {QStringLiteral("加载媒体超时"), QStringLiteral("Timed out loading media")},
        {QStringLiteral("名称 A→Z"), QStringLiteral("Name A→Z")},
        {QStringLiteral("名称 Z→A"), QStringLiteral("Name Z→A")},
        {QStringLiteral("备注: %1"), QStringLiteral("Note: %1")},
        {QStringLiteral("复制片段信息"), QStringLiteral("Copy clip info")},
        {QStringLiteral("媒体库已刷新"), QStringLiteral("Media library refreshed")},
        {QStringLiteral("媒体库文件夹"), QStringLiteral("Media library folders")},
        {QStringLiteral("媒体库管理…"), QStringLiteral("Media library manager…")},
        {QStringLiteral("安全（推荐）"), QStringLiteral("Safe (recommended)")},
        {QStringLiteral("展开循环列表"), QStringLiteral("Expand loop list")},
        {QStringLiteral("当前脚本位置"), QStringLiteral("Current script position")},
        {QStringLiteral("循环列表管理"), QStringLiteral("Loop list manager")},
        {QStringLiteral("打开文件夹…"), QStringLiteral("Open folder…")},
        {QStringLiteral("打开日志目录"), QStringLiteral("Open log folder")},
        {QStringLiteral("折叠循环列表"), QStringLiteral("Collapse loop list")},
        {QStringLiteral("搜索文件名…"), QStringLiteral("Search file names…")},
        {QStringLiteral("收藏夹不存在"), QStringLiteral("Collection not found")},
        {QStringLiteral("收藏夹名称："), QStringLiteral("Collection name:")},
        {QStringLiteral("收藏夹：%1"), QStringLiteral("Collections: %1")},
        {QStringLiteral("断开 SR6"), QStringLiteral("Disconnect SR6")},
        {QStringLiteral("新建收藏夹…"), QStringLiteral("New collection…")},
        {QStringLiteral("日期 新→旧"), QStringLiteral("Date newest→oldest")},
        {QStringLiteral("日期 旧→新"), QStringLiteral("Date oldest→newest")},
        {QStringLiteral("时长 短→长"), QStringLiteral("Length short→long")},
        {QStringLiteral("时长 长→短"), QStringLiteral("Length long→short")},
        {QStringLiteral("显示全部标签"), QStringLiteral("Show all tags")},
        {QStringLiteral("显示全部视频"), QStringLiteral("Show all videos")},
        {QStringLiteral("显示循环列表"), QStringLiteral("Show loop list")},
        {QStringLiteral("暂时无法清理"), QStringLiteral("Cannot clean up yet")},
        {QStringLiteral("未生成缩略图"), QStringLiteral("No thumbnail was produced")},
        {QStringLiteral("未能截取画面"), QStringLiteral("Could not grab a frame")},
        {QStringLiteral("本次启动时长"), QStringLiteral("Session uptime")},
        {QStringLiteral("标签: %1"), QStringLiteral("Tags: %1")},
        {QStringLiteral("标签「%1」"), QStringLiteral("Tag \"%1\"")},
        {QStringLiteral("标签不能为空"), QStringLiteral("Tag cannot be empty")},
        {QStringLiteral("添加 新→旧"), QStringLiteral("Added newest→oldest")},
        {QStringLiteral("添加 旧→新"), QStringLiteral("Added oldest→newest")},
        {QStringLiteral("添加循环片段"), QStringLiteral("Add loop clip")},
        {QStringLiteral("添加文件夹…"), QStringLiteral("Add folder…")},
        {QStringLiteral("清理失效数据"), QStringLiteral("Clean up missing data")},
        {QStringLiteral("清理失效片段"), QStringLiteral("Clean up missing clips")},
        {QStringLiteral("清除全部标记"), QStringLiteral("Clear all markers")},
        {QStringLiteral("片段已被删除"), QStringLiteral("The clip was deleted")},
        {QStringLiteral("移除所选标签"), QStringLiteral("Remove selected tags")},
        {QStringLiteral("管理收藏夹…"), QStringLiteral("Manage collections…")},
        {QStringLiteral("编辑循环片段"), QStringLiteral("Edit loop clip")},
        {QStringLiteral("自动（推荐）"), QStringLiteral("Automatic (recommended)")},
        {QStringLiteral("轴校准与测试"), QStringLiteral("Axis calibration and test")},
        {QStringLiteral("连接 SR6"), QStringLiteral("Connect SR6")},
        {QStringLiteral("连续播放片段"), QStringLiteral("Auto-next clips")},
        {QStringLiteral("选择跳转速度"), QStringLiteral("Choose the seek speed")},
        {QStringLiteral("重命名收藏夹"), QStringLiteral("Rename collection")},
        {QStringLiteral(" 蓝牙：%1。"), QStringLiteral(" Bluetooth: %1.")},
        {QStringLiteral("%1 · 蓝牙"), QStringLiteral("%1 · Bluetooth")},
        {QStringLiteral("(控制器折叠="), QStringLiteral("(controller collapsed=")},
        {QStringLiteral("使用自定义参数"), QStringLiteral("Use custom parameters")},
        {QStringLiteral("保存到当前配置"), QStringLiteral("Save into current profile")},
        {QStringLiteral("停止生成缩略图"), QStringLiteral("Stop generating thumbnails")},
        {QStringLiteral("切换收藏夹视图"), QStringLiteral("Switch collection view")},
        {QStringLiteral("删除循环收藏夹"), QStringLiteral("Delete loop collection")},
        {QStringLiteral("吸吮行程 A0"), QStringLiteral("Suck stroke A0")},
        {QStringLiteral("媒体库自动连播"), QStringLiteral("Media library auto-next")},
        {QStringLiteral("导入轴限制配置"), QStringLiteral("Import axis limit profiles")},
        {QStringLiteral("导出轴限制配置"), QStringLiteral("Export axis limit profiles")},
        {QStringLiteral("已关闭自动连播"), QStringLiteral("Auto-next disabled")},
        {QStringLiteral("已删除循环片段"), QStringLiteral("Loop clip deleted")},
        {QStringLiteral("已发送复位指令"), QStringLiteral("Reset command sent")},
        {QStringLiteral("已开启自动连播"), QStringLiteral("Auto-next enabled")},
        {QStringLiteral("已终止当前视频"), QStringLiteral("Current video stopped")},
        {QStringLiteral("循环列表管理…"), QStringLiteral("Loop list manager…")},
        {QStringLiteral("循环播放此片段"), QStringLiteral("Loop this clip")},
        {QStringLiteral("循环片段不存在"), QStringLiteral("Loop clip not found")},
        {QStringLiteral("循环片段已更新"), QStringLiteral("Loop clip updated")},
        {QStringLiteral("打开媒体文件夹"), QStringLiteral("Open media folder")},
        {QStringLiteral("打开所在文件夹"), QStringLiteral("Open containing folder")},
        {QStringLiteral("收藏夹不可用。"), QStringLiteral("The collection is not available.")},
        {QStringLiteral("收藏夹未能保存"), QStringLiteral("The collection could not be saved")},
        {QStringLiteral("新建循环收藏夹"), QStringLiteral("New loop collection")},
        {QStringLiteral("新建收藏夹失败"), QStringLiteral("Could not create the collection")},
        {QStringLiteral("无效的媒体路径"), QStringLiteral("Invalid media path")},
        {QStringLiteral("无法创建收藏夹"), QStringLiteral("Could not create the collection")},
        {QStringLiteral("无法删除收藏夹"), QStringLiteral("Could not delete the collection")},
        {QStringLiteral("无法加入收藏夹"), QStringLiteral("Could not add to the collection")},
        {QStringLiteral("无法连接 %1"), QStringLiteral("Cannot connect to %1")},
        {QStringLiteral("未知轨道：%1"), QStringLiteral("Unknown track: %1")},
        {QStringLiteral("正在检测端口…"), QStringLiteral("Detecting ports…")},
        {QStringLiteral("测试 100%"), QStringLiteral("Test 100%")},
        {QStringLiteral("清理失效数据…"), QStringLiteral("Clean up missing data…")},
        {QStringLiteral("清理未使用标签"), QStringLiteral("Clean up unused tags")},
        {QStringLiteral("清理缩略图缓存"), QStringLiteral("Clear thumbnail cache")},
        {QStringLiteral("清除 B 标记"), QStringLiteral("Clear the B marker")},
        {QStringLiteral("移出所有收藏夹"), QStringLiteral("Remove from all collections")},
        {QStringLiteral("缓动已全部关闭"), QStringLiteral("All easing is now off")},
        {QStringLiteral("缓动设置已更新"), QStringLiteral("Easing settings updated")},
        {QStringLiteral("蓝牙 · %1"), QStringLiteral("Bluetooth · %1")},
        {QStringLiteral("蓝牙地址 %1"), QStringLiteral("Bluetooth address %1")},
        {QStringLiteral("轴校准与测试…"), QStringLiteral("Axis calibration and test…")},
        {QStringLiteral("连接或断开设备"), QStringLiteral("Connect or disconnect the device")},
        {QStringLiteral("重新生成缩略图"), QStringLiteral("Regenerate thumbnail")},
        {QStringLiteral("（注册表条目）"), QStringLiteral("(registry entry)")},
        {QStringLiteral("（还没有标签）"), QStringLiteral("(No tags yet)")},
        {QStringLiteral(" / 失效 %1"), QStringLiteral(" / missing %1")},
        {QStringLiteral("修改日期 新→旧"), QStringLiteral("Modified newest→oldest")},
        {QStringLiteral("修改日期 旧→新"), QStringLiteral("Modified oldest→newest")},
        {QStringLiteral("全部恢复默认限位"), QStringLiteral("Restore default limits everywhere")},
        {QStringLiteral("复位（回到中位）"), QStringLiteral("Reset (back to centre)")},
        {QStringLiteral("已停止生成缩略图"), QStringLiteral("Thumbnail generation stopped")},
        {QStringLiteral("已应用轴限制配置"), QStringLiteral("Axis limit profile applied")},
        {QStringLiteral("已标记 A：%1"), QStringLiteral("Marked A: %1")},
        {QStringLiteral("已标记 B：%1"), QStringLiteral("Marked B: %1")},
        {QStringLiteral("已清除 B 标记"), QStringLiteral("B marker cleared")},
        {QStringLiteral("循环片段已被删除"), QStringLiteral("The loop clip was deleted")},
        {QStringLiteral("按循环收藏夹筛选"), QStringLiteral("Filter by loop collection")},
        {QStringLiteral("收藏夹与循环片段"), QStringLiteral("collections and loop clips")},
        {QStringLiteral("收藏夹已经在%1"), QStringLiteral("Already in %1")},
        {QStringLiteral("无法创建临时目录"), QStringLiteral("Cannot create a temporary directory")},
        {QStringLiteral("无法连接 SR6"), QStringLiteral("Cannot connect to SR6")},
        {QStringLiteral("无法重命名收藏夹"), QStringLiteral("Could not rename the collection")},
        {QStringLiteral("时间点不能为负数"), QStringLiteral("Time cannot be negative")},
        {QStringLiteral("显示全部循环片段"), QStringLiteral("Show all loop clips")},
        {QStringLiteral("未知轴标识：%1"), QStringLiteral("Unknown axis id: %1")},
        {QStringLiteral("标签名称不能为空"), QStringLiteral("Tag name cannot be empty")},
        {QStringLiteral("没有找到同名文件"), QStringLiteral("No file with the same name was found")},
        {QStringLiteral("注册表记录的串口"), QStringLiteral("Port from the registry")},
        {QStringLiteral("添加媒体库文件夹"), QStringLiteral("Add media library folder")},
        {QStringLiteral("添加循环片段失败"), QStringLiteral("Could not add the loop clip")},
        {QStringLiteral("添加时间 新→旧"), QStringLiteral("Added newest→oldest")},
        {QStringLiteral("添加时间 旧→新"), QStringLiteral("Added oldest→newest")},
        {QStringLiteral("点击 #1 之后"), QStringLiteral("after click #1")},
        {QStringLiteral("点击 #2 之后"), QStringLiteral("after click #2")},
        {QStringLiteral("片段时长 短→长"), QStringLiteral("Clip length short→long")},
        {QStringLiteral("片段时长 长→短"), QStringLiteral("Clip length long→short")},
        {QStringLiteral("片段没有关联视频"), QStringLiteral("The clip has no video attached")},
        {QStringLiteral("管理循环收藏夹…"), QStringLiteral("Manage loop collections…")},
        {QStringLiteral("缩略图缓存与索引"), QStringLiteral("thumbnail cache and index")},
        {QStringLiteral("缩略图缓存已清理"), QStringLiteral("Thumbnail cache cleared")},
        {QStringLiteral("蓝牙设备：%1\n"), QStringLiteral("Bluetooth device: %1\n")},
        {QStringLiteral("视频名称 A→Z"), QStringLiteral("Video name A→Z")},
        {QStringLiteral("视频名称 Z→A"), QStringLiteral("Video name Z→A")},
        {QStringLiteral("设备未提供端口名"), QStringLiteral("The device did not provide a port name")},
        {QStringLiteral("请先打开一个视频"), QStringLiteral("Open a video first")},
        {QStringLiteral("请先标记起点 A"), QStringLiteral("Mark start A first")},
        {QStringLiteral("重命名循环收藏夹"), QStringLiteral("Rename loop collection")},
        {QStringLiteral("重新关联失效条目"), QStringLiteral("Relink missing entries")},
        {QStringLiteral("（还没有收藏夹）"), QStringLiteral("(No collections yet)")},
        {QStringLiteral("mpv 初始化失败"), QStringLiteral("mpv initialization failed")},
        {QStringLiteral("同步 ±%1 ms"), QStringLiteral("Sync ±%1 ms")},
        {QStringLiteral("向右拖动展开媒体库"), QStringLiteral("Drag right to expand the media library")},
        {QStringLiteral("在资源管理器中打开"), QStringLiteral("Open in Explorer")},
        {QStringLiteral("已从所有收藏夹移除"), QStringLiteral("Removed from every collection")},
        {QStringLiteral("已播放到媒体库末尾"), QStringLiteral("Reached the end of the media library")},
        {QStringLiteral("所有轴回到行程中点"), QStringLiteral("Move every axis back to the middle of its travel")},
        {QStringLiteral("播放联动中不可复位"), QStringLiteral("Cannot reset while playback is driving the device")},
        {QStringLiteral("播放（Space）"), QStringLiteral("Play (Space)")},
        {QStringLiteral("收藏夹名称不能为空"), QStringLiteral("Collection name cannot be empty")},
        {QStringLiteral("无法打开脚本：%1"), QStringLiteral("Cannot open script: %1")},
        {QStringLiteral("显示单轴/多轴标签"), QStringLiteral("Show axis-count badges")},
        {QStringLiteral("暂停（Space）"), QStringLiteral("Pause (Space)")},
        {QStringLiteral("每 1% 行程耗时"), QStringLiteral("Time per 1% of travel")},
        {QStringLiteral("没有未使用的标签。"), QStringLiteral("There are no unused tags.")},
        {QStringLiteral("清理此条失效记录…"), QStringLiteral("Clean up this missing entry…")},
        {QStringLiteral("清除 A/B 标记"), QStringLiteral("Clear A/B markers")},
        {QStringLiteral("画面中间（应收起）"), QStringLiteral("centre of the picture (should retract)")},
        {QStringLiteral("系统里没有这个端口"), QStringLiteral("No such port on this system")},
        {QStringLiteral("自动（播放时生效）"), QStringLiteral("Automatic (applies on playback)")},
        {QStringLiteral("蓝牙串口 · %1"), QStringLiteral("Bluetooth serial · %1")},
        {QStringLiteral("这个端口连不上设备"), QStringLiteral("This port cannot reach a device")},
        {QStringLiteral("连接设备后才能试位"), QStringLiteral("Connect a device to test positions")},
        {QStringLiteral("重新关联到新位置…"), QStringLiteral("Relink to a new location…")},
        {QStringLiteral("重新关联失效条目…"), QStringLiteral("Relink missing entries…")},
        {QStringLiteral("重新生成全部缩略图"), QStringLiteral("Regenerate all thumbnails")},
        {QStringLiteral("静音 / 取消静音"), QStringLiteral("Mute / unmute")},
        {QStringLiteral("%1（%2 个片段）"), QStringLiteral("%1 (%2 clips)")},
        {QStringLiteral("只显示没有标签的片段"), QStringLiteral("Show only clips without tags")},
        {QStringLiteral("向左拖动展开循环列表"), QStringLiteral("Drag left to expand the loop list")},
        {QStringLiteral("多个同名候选，请选择"), QStringLiteral("Several candidates share this name; pick one")},
        {QStringLiteral("已加入收藏夹「%1」"), QStringLiteral("Added to collection \"%1\"")},
        {QStringLiteral("已添加循环片段：%1"), QStringLiteral("Loop clip added: %1")},
        {QStringLiteral("已清除 A/B 标记"), QStringLiteral("A/B markers cleared")},
        {QStringLiteral("正在重新生成缩略图…"), QStringLiteral("Regenerating thumbnails…")},
        {QStringLiteral("没有失效条目需要关联"), QStringLiteral("No missing entries to relink")},
        {QStringLiteral("没有找到失效的条目。"), QStringLiteral("No missing entries were found.")},
        {QStringLiteral("结束时间超出视频长度"), QStringLiteral("End time is past the end of the video")},
        {QStringLiteral("脚本中没有可用动作点"), QStringLiteral("The script has no usable action points")},
        {QStringLiteral("视频文件 (*.*)"), QStringLiteral("Video files (*.*)")},
        {QStringLiteral("设备连接已丢失：%1"), QStringLiteral("Device connection lost: %1")},
        {QStringLiteral("还没有勾选任何条目。"), QStringLiteral("Nothing is ticked yet.")},
        {QStringLiteral("（还没有循环收藏夹）"), QStringLiteral("(No loop collections yet)")},
        {QStringLiteral("B 点必须晚于 A 点"), QStringLiteral("B must be later than A")},
        {QStringLiteral("Qt 枚举到（未探测）"), QStringLiteral("Reported by Qt (not probed)")},
        {QStringLiteral("· 循环片段 %1 个"), QStringLiteral("· %1 loop clips")},
        {QStringLiteral("全局行程比例与多套配置"), QStringLiteral("Global travel ratio with multiple profiles")},
        {QStringLiteral("关于 NekoBeat"), QStringLiteral("About NekoBeat")},
        {QStringLiteral("切换已保存的轴限制配置"), QStringLiteral("Switch between saved travel profiles")},
        {QStringLiteral("在资源管理器中显示视频"), QStringLiteral("Show the video in Explorer")},
        {QStringLiteral("已从收藏夹「%1」移除"), QStringLiteral("Removed from collection \"%1\"")},
        {QStringLiteral("已应用 %1 的校准值"), QStringLiteral("Applied the calibration values for %1")},
        {QStringLiteral("已清理 %1 个标签。"), QStringLiteral("Removed %1 tags.")},
        {QStringLiteral("当前没有 A/B 标记"), QStringLiteral("There are no A/B markers")},
        {QStringLiteral("所有片段的视频文件都在"), QStringLiteral("Every clip still has its video file")},
        {QStringLiteral("搜索片段、标签、备注…"), QStringLiteral("Search clips, tags, notes…")},
        {QStringLiteral("文件里没有可用的配置。"), QStringLiteral("The file contains no usable profiles.")},
        {QStringLiteral("无法创建 mpv 实例"), QStringLiteral("Cannot create the mpv instance")},
        {QStringLiteral("无法打开（错误 %1）"), QStringLiteral("Cannot open (error %1)")},
        {QStringLiteral("无法配置 mpv 输出"), QStringLiteral("Cannot configure the mpv output")},
        {QStringLiteral("正在加载循环片段：%1"), QStringLiteral("Loading loop clip: %1")},
        {QStringLiteral("清除当前 A/B 标记"), QStringLiteral("Clear the current A/B markers")},
        {QStringLiteral("片段信息已复制到剪贴板"), QStringLiteral("Clip info copied to the clipboard")},
        {QStringLiteral("移出当前收藏夹「%1」"), QStringLiteral("Remove from current collection \"%1\"")},
        {QStringLiteral("至少需要保留一个配置。"), QStringLiteral("At least one profile must remain.")},
        {QStringLiteral("蓝牙串口（已配对设备）"), QStringLiteral("Bluetooth serial (paired device)")},
        {QStringLiteral("退出后点击 #1 之后"), QStringLiteral("after click #1 following the exit")},
        {QStringLiteral("退出后点击 #2 之后"), QStringLiteral("after click #2 following the exit")},
        {QStringLiteral("\n\n备份已保存到：\n%1"), QStringLiteral("\n\nBackup saved to:\n%1")},
        {QStringLiteral("%1  ·  有效 %2"), QStringLiteral("%1  ·  valid %2")},
        {QStringLiteral("%1 | %2 轴：%3"), QStringLiteral("%1 | %2 axes: %3")},
        {QStringLiteral("交换媒体库与循环列表位置"), QStringLiteral("Swap the media library and loop list")},
        {QStringLiteral("右边缘下部（旧版会失效）"), QStringLiteral("right edge, lower (broken in older builds)")},
        {QStringLiteral("启用跳转安全缓动（推荐）"), QStringLiteral("Enable seek-safety easing (recommended)")},
        {QStringLiteral("左边缘下部（旧版会失效）"), QStringLiteral("left edge, lower (broken in older builds)")},
        {QStringLiteral("已存在同名收藏夹「%1」"), QStringLiteral("A collection named \"%1\" already exists")},
        {QStringLiteral("已移除媒体库文件夹：%1"), QStringLiteral("Removed media library folder: %1")},
        {QStringLiteral("已重新关联 %1 条记录"), QStringLiteral("Relinked %1 entries")},
        {QStringLiteral("折叠探针: 进入完全全屏"), QStringLiteral("Fold probe: enter true full screen")},
        {QStringLiteral("折叠探针: 退出完全全屏"), QStringLiteral("Fold probe: leave true full screen")},
        {QStringLiteral("播放 / 暂停也使用缓动"), QStringLiteral("Ease play / pause too")},
        {QStringLiteral("新建配置（复制当前限位）"), QStringLiteral("New profile (copy current limits)")},
        {QStringLiteral("无法打开 %1。\n\n%2"), QStringLiteral("Cannot open %1.\n\n%2")},
        {QStringLiteral("无法打开串口 %1：%2"), QStringLiteral("Cannot open serial port %1: %2")},
        {QStringLiteral("确定删除配置“%1”吗？"), QStringLiteral("Delete profile \"%1\"?")},
        {QStringLiteral("蓝牙串口（本机入站端口）"), QStringLiteral("Bluetooth serial (local inbound port)")},
        {QStringLiteral("请先连接设备，再执行复位"), QStringLiteral("Connect a device before resetting")},
        {QStringLiteral("退出全屏后 0.65 秒"), QStringLiteral("0.65 s after leaving full screen")},
        {QStringLiteral("名称为空或与现有配置重复。"), QStringLiteral("The name is empty or duplicates an existing profile.")},
        {QStringLiteral("将重新关联 %1 条记录。"), QStringLiteral("%1 entries will be relinked.")},
        {QStringLiteral("已导入 %1 个配置：%2"), QStringLiteral("Imported %1 profiles: %2")},
        {QStringLiteral("当前限位已保存为“%1”。"), QStringLiteral("Current limits saved as \"%1\".")},
        {QStringLiteral("循环中：%1（%2–%3）"), QStringLiteral("Looping: %1 (%2–%3)")},
        {QStringLiteral("折叠探针结束（步数 %1）"), QStringLiteral("Fold probe finished (%1 steps)")},
        {QStringLiteral("标签不能超过 %1 个字符"), QStringLiteral("Tag cannot exceed %1 characters")},
        {QStringLiteral("脚本文件过大，已跳过：%1"), QStringLiteral("Script file is too large, skipped: %1")},
        {QStringLiteral("被其他程序占用（拒绝访问）"), QStringLiteral("In use by another program (access denied)")},
        {QStringLiteral("设备已断开，播放联动已停止"), QStringLiteral("Device disconnected; playback sync stopped")},
        {QStringLiteral("选择脚本（可进入子文件夹）"), QStringLiteral("Choose a script (subfolders allowed)")},
        {QStringLiteral("驱动异常（问题代码 %1）"), QStringLiteral("Driver problem (problem code %1)")},
        {QStringLiteral("串口持续拥堵，播放联动已停止"), QStringLiteral("The serial link stayed congested; playback sync stopped")},
        {QStringLiteral("只显示不属于任何收藏夹的视频"), QStringLiteral("Show only videos in no collection")},
        {QStringLiteral("已离开循环区间，退出循环播放"), QStringLiteral("Left the loop range; loop playback stopped")},
        {QStringLiteral("播放 / 暂停（Space）"), QStringLiteral("Play / pause (Space)")},
        {QStringLiteral("标签数量已达上限（%1 个）"), QStringLiteral("Tag limit reached (%1).")},
        {QStringLiteral("界面语言，切换后重新启动生效"), QStringLiteral("Interface language; a restart applies the change")},
        {QStringLiteral("会真实驱动设备，请确认周围安全"), QStringLiteral("This really moves the device. Make sure the area is clear")},
        {QStringLiteral("在控制栏下方显示脚本动作热力图"), QStringLiteral("Draw the script heat map below the control bar")},
        {QStringLiteral("循环回跳未生效，已退出循环播放"), QStringLiteral("The loop rewind did not take effect; loop playback stopped")},
        {QStringLiteral("收藏夹「%1」（%2 个视频）"), QStringLiteral("Collection \"%1\" (%2 videos)")},
        {QStringLiteral("收藏夹数量已达上限（%1 个）"), QStringLiteral("Collection limit reached (%1).")},
        {QStringLiteral("旧数据仍在 %1（迁移未完成）"), QStringLiteral("Old data is still in %1 (migration unfinished)")},
        {QStringLiteral("有 %1 个片段找不到视频文件"), QStringLiteral("%1 clips point at a missing video file")},
        {QStringLiteral("正在重新生成 %1 个缩略图…"), QStringLiteral("Regenerating %1 thumbnails…")},
        {QStringLiteral("行程下限：脚本 0% 对应这里"), QStringLiteral("Lower limit: script 0% maps here")},
        {QStringLiteral("视频文件不存在，无法播放该片段"), QStringLiteral("The video file is missing, so this clip cannot play")},
        {QStringLiteral("配置“%1”已存在，是否覆盖？"), QStringLiteral("Profile \"%1\" already exists. Overwrite it?")},
        {QStringLiteral("JSON 配置 (*.json)"), QStringLiteral("JSON profiles (*.json)")},
        {QStringLiteral("串口接收缓存溢出，已丢弃残留数据"), QStringLiteral("Serial receive buffer overflowed; leftover data was dropped")},
        {QStringLiteral("只显示不属于任何循环收藏夹的片段"), QStringLiteral("Show only clips that belong to no loop collection")},
        {QStringLiteral("已新建收藏夹「%1」并加入该视频"), QStringLiteral("Created collection \"%1\" and added this video to it")},
        {QStringLiteral("已迁移%1（补入 %2 个文件）"), QStringLiteral("Moved %1 (%2 files added)")},
        {QStringLiteral("循环片段太短（至少 %1 毫秒）"), QStringLiteral("Loop clip is too short (at least %1 ms)")},
        {QStringLiteral("折叠探针: 退出全屏后点击 #1"), QStringLiteral("Fold probe: click #1 after leaving full screen")},
        {QStringLiteral("折叠探针: 退出全屏后点击 #2"), QStringLiteral("Fold probe: click #2 after leaving full screen")},
        {QStringLiteral("收藏夹名称不能超过 %1 个字符"), QStringLiteral("Collection name cannot exceed %1 characters")},
        {QStringLiteral("正在识别设备支持的轴，请稍候再试"), QStringLiteral("Still detecting the supported axes; try again in a moment")},
        {QStringLiteral("该脚本没有可用动作，已按视频播放"), QStringLiteral("That script has no usable actions; playing the video instead")},
        {QStringLiteral("高级自定义（仅供了解参数的用户）"), QStringLiteral("Advanced (for people who know the parameters)")},
        {QStringLiteral("已自动交换 A/B：%1 – %2"), QStringLiteral("A and B were swapped automatically: %1 – %2")},
        {QStringLiteral("循环收藏夹「%1」（%2 个片段）"), QStringLiteral("Loop collection \"%1\" (%2 clips)")},
        {QStringLiteral("播放联动中不可复位，请先暂停或终止"), QStringLiteral("Cannot reset while playback is driving the device; pause or stop first")},
        {QStringLiteral("播放联动中不可校准，请先暂停或终止"), QStringLiteral("Cannot calibrate while playback is driving the device; pause or stop first")},
        {QStringLiteral("未收到有效的 TCode 握手响应"), QStringLiteral("No valid TCode handshake response")},
        {QStringLiteral("标签「%1」不能超过 %2 个字符"), QStringLiteral("Tag \"%1\" cannot exceed %2 characters")},
        {QStringLiteral("行程上限：脚本 100% 对应这里"), QStringLiteral("Upper limit: script 100% maps here")},
        {QStringLiteral("解码方式已保存，下次打开视频时生效"), QStringLiteral("Decoding mode saved; it applies the next time a video is opened")},
        {QStringLiteral("记录每条 TCode 命令（诊断）"), QStringLiteral("Log every TCode command (diagnostics)")},
        {QStringLiteral("配置“%1”已存在，请换一个名称。"), QStringLiteral("Profile \"%1\" already exists. Pick another name.")},
        {QStringLiteral("一段播完自动接着播当前列表里的下一段"), QStringLiteral("Play the next clip in the list when one ends")},
        {QStringLiteral("动作点超过 %1 个，多余部分已忽略"), QStringLiteral("More than %1 action points; the rest were ignored")},
        {QStringLiteral("取消当前的 A/B 标记，不保存片段"), QStringLiteral("Clear the current A/B markers without saving a clip")},
        {QStringLiteral("同时作用于媒体库与循环列表的封面尺寸"), QStringLiteral("Cover size for both the media library and the loop list")},
        {QStringLiteral("折叠探针: 点击折叠/展开按钮 #1"), QStringLiteral("Fold probe: click the fold/expand button #1")},
        {QStringLiteral("折叠探针: 点击折叠/展开按钮 #2"), QStringLiteral("Fold probe: click the fold/expand button #2")},
        {QStringLiteral("标记循环终点 B（]）\n右键清除标记"), QStringLiteral("Mark loop end B ( ] )\nRight-click to clear")},
        {QStringLiteral("标记循环终点 B（]）\n需先标记 A"), QStringLiteral("Mark loop end B ( ] )\nMark A first")},
        {QStringLiteral("标记循环起点 A（[）\n右键清除标记"), QStringLiteral("Mark loop start A ( [ )\nRight-click to clear")},
        {QStringLiteral("留空则自动使用「视频名 · 时间段」"), QStringLiteral("Leave empty to use \"video name · time range\"")},
        {QStringLiteral("脚本 JSON 无效：%1 (%2)"), QStringLiteral("Invalid script JSON: %1 (%2)")},
        {QStringLiteral("设备存在，但没有可用的 COM 名称"), QStringLiteral("The device exists but exposes no usable COM name")},
        {QStringLiteral("%1\n%2固件：%3\nTCode：%4"), QStringLiteral("%1\n%2Firmware: %3\nTCode: %4")},
        {QStringLiteral("NekoBeat-轴限制配置.json"), QStringLiteral("NekoBeat-axis-limits.json")},
        {QStringLiteral("切换全屏时画面闪白的话，选“软件解码”"), QStringLiteral("If the picture flashes white when switching to full screen, pick \"Software decoding\"")},
        {QStringLiteral("同时作用于媒体库与循环列表的文件名字号"), QStringLiteral("File-name font size for both the media library and the loop list")},
        {QStringLiteral("已开启 TCode 逐条日志（诊断用）"), QStringLiteral("Per-command TCode logging enabled (diagnostics)")},
        {QStringLiteral("收藏夹未能保存，请检查磁盘权限后重试。"), QStringLiteral("The collection could not be saved. Check the disk permissions and try again.")},
        {QStringLiteral("标记循环起点 A（[）\n点击时自动暂停"), QStringLiteral("Mark loop start A ( [ )\nPlayback pauses automatically")},
        {QStringLiteral("能用硬件解码就用，失败自动回退软件解码"), QStringLiteral("Use hardware decoding when possible, fall back to software automatically")},
        {QStringLiteral("· 标签 %1 个（已没有其他片段使用）"), QStringLiteral("· %1 tags (no longer used by any clip)")},
        {QStringLiteral("取消当前的 A/B 标记（不会保存片段）"), QStringLiteral("Clear the current A/B markers (no clip is saved)")},
        {QStringLiteral("在媒体库与循环列表的文件名前显示脚本轴数"), QStringLiteral("Show the script axis count in front of file names in the media library and loop list")},
        {QStringLiteral("尝试更多硬件解码后端，失败仍回退软件解码"), QStringLiteral("Try more hardware backends, still falling back to software")},
        {QStringLiteral("正在识别设备支持的轴，识别完成前不会联动"), QStringLiteral("Detecting the axes this device supports; nothing is driven until that finishes")},
        {QStringLiteral("\n⚠ 这些位置当前打不开，清理已暂停：%1"), QStringLiteral("\n⚠ These locations cannot be opened right now, so clean-up is paused: %1")},
        {QStringLiteral("%1(可见=%2 %3,%4 %5x%6)"), QStringLiteral("%1(visible=%2 %3,%4 %5x%6)")},
        {QStringLiteral("一个视频播完自动接着播媒体库列表里的下一个"), QStringLiteral("Play the next video in the media library when one ends")},
        {QStringLiteral("已标记 A %1，B 早于 A 已自动清除"), QStringLiteral("Marked A at %1; B was earlier than A and has been cleared")},
        {QStringLiteral("拖入视频文件，或使用“文件 › 打开视频”"), QStringLiteral("Drop a video file here, or use \"File › Open video\"")},
        {QStringLiteral("设备指令与脚本时基的偏差（每 5 秒更新）"), QStringLiteral("Worst lag between device commands and the script clock (updated every 5 s)")},
        {QStringLiteral("输入标签后回车，可一次输入多个（逗号分隔）"), QStringLiteral("Type a tag and press Enter; separate several with commas")},
        {QStringLiteral("连续播放：一段播完自动接着播列表里的下一段"), QStringLiteral("Auto-next: play the next clip in the list when one ends")},
        {QStringLiteral("（还没有循环收藏夹，可点“新建收藏夹…”）"), QStringLiteral("(No loop collections yet - use \"New collection…\")")},
        {QStringLiteral("50% 行程约 %1，100% 行程约 %2"), QStringLiteral("About %1 for 50% of the travel and %2 for 100%")},
        {QStringLiteral("已关闭 TCode 逐条日志，仅保留联动统计"), QStringLiteral("Per-command TCode logging disabled; only the link summary remains")},
        {QStringLiteral("文件不是有效的 NekoBeat 配置：%1"), QStringLiteral("Not a valid NekoBeat profile file: %1")},
        {QStringLiteral("片段太短（至少 %1 毫秒），请重新标记 B"), QStringLiteral("The clip is too short (at least %1 ms); mark B again")},
        {QStringLiteral("%1@%2,%3 左=%4 中=%5 右=%6"), QStringLiteral("%1@%2,%3 left=%4 centre=%5 right=%6")},
        {QStringLiteral("循环终点 B：%1\n点击重新标记，右键清除标记"), QStringLiteral("Loop end B: %1\nClick to re-mark, right-click to clear")},
        {QStringLiteral("循环起点 A：%1\n点击重新标记，右键清除标记"), QStringLiteral("Loop start A: %1\nClick to re-mark, right-click to clear")},
        {QStringLiteral("把 A-B 区间保存为循环片段（Ctrl+L）"), QStringLiteral("Save the A-B range as a loop clip (Ctrl+L)")},
        {QStringLiteral("把循环列表放到左侧、媒体库放到右侧（默认相反）"), QStringLiteral("Put the loop list on the left and the media library on the right (the default is the other way around)")},
        {QStringLiteral("拖动两端设置行程比例，设备会跟随移动到限位位置"), QStringLiteral("Drag the two ends to set the travel ratio; the device follows to that limit")},
        {QStringLiteral("连续播放：一个视频播完自动接着播列表里的下一个"), QStringLiteral("Auto-next: play the next video in the list when one ends")},
        {QStringLiteral("· 收藏夹记录 %1 条（涉及 %2 个收藏夹）"), QStringLiteral("· %1 collection entries (across %2 collections)")},
        {QStringLiteral("一次清掉失效的收藏记录、循环片段和不再使用的标签"), QStringLiteral("Remove missing collection entries, loop clips and unused tags in one pass")},
        {QStringLiteral("串口发送积压超过 %1 KB，设备可能已停止响应"), QStringLiteral("Serial send backlog exceeded %1 KB; the device may have stopped responding")},
        {QStringLiteral("保存 %1 – %2 为循环片段（Ctrl+L）"), QStringLiteral("Save %1 – %2 as a loop clip (Ctrl+L)")},
        {QStringLiteral("后面没有设备，连不上；请选带设备名的那个蓝牙串口"), QStringLiteral("No device behind this port. Pick the Bluetooth serial port that carries the device name.")},
        {QStringLiteral("当前约：50% 行程 %1，100% 行程 %2"), QStringLiteral("Currently about %1 for 50% of the travel and %2 for 100%")},
        {QStringLiteral("已急停：设备已停止，视频已暂停（再按播放即可恢复）"), QStringLiteral("Panic stop: the device has stopped and the video is paused (press play to resume)")},
        {QStringLiteral("已把旧的界面设置、轴限制与媒体库配置迁移到新名字下"), QStringLiteral("Moved the old settings, axis limits and media library configuration over to the new name")},
        {QStringLiteral("关闭时只记录每 5 秒的联动统计；排查串口问题时打开"), QStringLiteral("When off, only the 5-second link summary is logged; turn it on to debug serial problems")},
        {QStringLiteral("未找到匹配脚本，仅播放视频（右键卡片可手动选择脚本）"), QStringLiteral("No matching script found; playing the video only (right-click the card to pick a script)")},
        {QStringLiteral("关闭本程序仍持有的串口句柄并重新检测（不会动其它程序）"), QStringLiteral("Close the serial handles this program still owns and rescan (other programs are untouched)")},
        {QStringLiteral("删除片段「%1」？\n只删除这条收藏，不会影响视频文件。"), QStringLiteral("Delete clip \"%1\"?\nOnly this entry is removed; the video file is untouched.")},
        {QStringLiteral("整理过文件夹后，把失效的收藏与循环片段认到视频的新位置"), QStringLiteral("After reorganising folders, point missing collections and loop clips at the video's new location")},
        {QStringLiteral("全局生效 · 0–100% 按比例缩放行程，不会截断动作"), QStringLiteral("Global · scales the 0–100% travel proportionally, never truncating motion")},
        {QStringLiteral("共 %1 项：可用 %2、被占用 %3、驱动异常 %4。"), QStringLiteral("%1 ports: %2 ready, %3 in use, %4 with a driver problem.")},
        {QStringLiteral("跳转 / 切换的缓动速度，以及播放 / 暂停是否同样缓动"), QStringLiteral("Easing speed for seeks and switches, and whether play/pause eases too")},
        {QStringLiteral("先标记 A 和 B，再把区间保存为循环片段（Ctrl+L）"), QStringLiteral("Mark A and B first, then save the range as a loop clip (Ctrl+L)")},
        {QStringLiteral("删除标签「%1」？\n它会从所有片段上移除，片段本身会保留。"), QStringLiteral("Delete tag \"%1\"?\nIt is removed from every clip; the clips stay.")},
        {QStringLiteral("已清理 %1 条收藏记录、%2 个循环片段、%3 个标签。"), QStringLiteral("Removed %1 collection entries, %2 loop clips and %3 tags.")},
        {QStringLiteral("急停（Ctrl+Esc）\n立即发送 DSTOP 并暂停视频"), QStringLiteral("Panic stop (Ctrl+Esc)\nSends DSTOP immediately and pauses the video")},
        {QStringLiteral("逐轴设置最小/最大/归位/反向/时间偏移，并可驱动设备试位"), QStringLiteral("Per-axis minimum/maximum/home/invert/time offset, with buttons that drive the device")},
        {QStringLiteral("完全由 CPU 解码。切换全屏时若画面闪白，选这一项即可消除"), QStringLiteral("Decode entirely on the CPU. Choosing this removes the white flash when switching to full screen")},
        {QStringLiteral("时间码格式应为 mm:ss.mmm，例如 01:23.500"), QStringLiteral("Timecode must be mm:ss.mmm, for example 01:23.500")},
        {QStringLiteral("测试按钮会按上面的行程直接驱动设备，用于目视确认方向与限位。"), QStringLiteral("The test buttons drive the device through the travel above so you can confirm direction and limits by eye.")},
        {QStringLiteral("删除收藏夹「%1」？\n片段本身会保留，只是不再属于这个收藏夹。"), QStringLiteral("Delete collection \"%1\"?\nThe clips stay; they simply no longer belong to it.")},
        {QStringLiteral("未连接设备：可以先编辑并保存校准值，试位按钮连上设备后自动可用"), QStringLiteral("No device connected: you can edit and save the calibration values now; the test buttons become available once a device is connected")},
        {QStringLiteral("一个循环片段可以同时属于多个收藏夹；删除收藏夹不会删除片段本身。"), QStringLiteral("A loop clip can belong to several collections at once; deleting a collection never deletes the clip.")},
        {QStringLiteral("测试按钮会实际驱动设备。请确认设备周围安全，并保持可以随时断电。"), QStringLiteral("The test buttons really move the device. Keep the area clear and the power switch within reach.")},
        {QStringLiteral("界面语言已切换为 %1。\n重新启动后所有界面文字都会换成新语言。"), QStringLiteral("The interface language is now %1.\nAll interface text switches over after a restart.")},
        {QStringLiteral("设备未回应轴识别（D0/D1/D2），未开始联动；可断开后重连重试"), QStringLiteral("The device did not answer axis detection (D0/D1/D2); nothing is driven. Disconnect and reconnect to retry")},
        {QStringLiteral("重命名到已有标签会把两个标签合并；删除只会移除标签，不会删除片段。"), QStringLiteral("Renaming onto an existing tag merges the two; deleting only removes the tag, never the clip.")},
        {QStringLiteral("将删除本地缩略图与元数据缓存并重新生成，不会删除任何视频或脚本。继续？"), QStringLiteral("This deletes the local thumbnail and metadata cache and rebuilds it. No video or script is removed. Continue?")},
        {QStringLiteral("funscript 脚本 (*.funscript);;所有文件 (*.*)"), QStringLiteral("funscript files (*.funscript);;All files (*.*)")},
        {QStringLiteral("libmpv 初始化失败，请确认 libmpv-2.dll 已放在程序目录。"), QStringLiteral("libmpv failed to initialise. Make sure libmpv-2.dll sits next to the executable.")},
        {QStringLiteral("未连接设备：下面的数值可以现在填好并“应用”保存，连接设备后测试按钮会自动可用。"), QStringLiteral("No device connected: you can fill in the values below and save them with Apply; the test buttons become available once a device is connected.")},
        {QStringLiteral(" 设备在设备管理器里显示为黄色感叹号时，重新安装 USB 串口驱动后点“重新扫描”。"), QStringLiteral(" If Device Manager shows the device with a yellow mark, reinstall the USB serial driver and click Rescan.")},
        {QStringLiteral("软件每次启动和刷新时都会递归扫描这些文件夹，新复制的视频与脚本会自动出现在媒体库里。"), QStringLiteral("These folders are scanned recursively on every start and refresh, so newly copied videos and scripts appear in the library automatically.")},
        {QStringLiteral("<span style='color:#FF6961;'>视频文件已失效</span>"), QStringLiteral("<span style='color:#FF6961;'>Video file is missing</span>")},
        {QStringLiteral("以下记录将被删除，视频文件本身不会被删除：\n\n%1\n\n清理前会自动备份数据文件。继续？"), QStringLiteral("These entries will be deleted; the video files themselves are not:\n\n%1\n\nThe data files are backed up automatically before cleaning. Continue?")},
        {QStringLiteral(" 端口被占用：关闭串口助手 / Arduino IDE 之类的程序，或先点“强制释放”。"), QStringLiteral(" Port in use: close programs such as a serial monitor or the Arduino IDE, or click \"Force release\" first.")},
        {QStringLiteral("最近 %1 秒：%2 条指令，最大 tick 间隔 %3 ms，最大相位滞后 %4 ms"), QStringLiteral("Last %1 s: %2 commands, worst tick gap %3 ms, worst phase lag %4 ms")},
        {QStringLiteral("删除收藏夹「%1」？\n\n只移除这个收藏夹和其中的 %2 条收藏记录，不会删除任何视频或脚本文件。"), QStringLiteral("Delete collection \"%1\"?\n\nThis only removes the collection and its %2 entries; no video or script file is deleted.")},
        {QStringLiteral(" 记住宽=%1 面板可见=%2 侧栏可见=%3 侧栏宽=%4 按钮可见=%5 %6x%7 命中=%8)"), QStringLiteral(" rememberedWidth=%1 panelVisible=%2 sideVisible=%3 sideWidth=%4 buttonVisible=%5 %6x%7 hit=%8)")},
        {QStringLiteral("这些位置当前打不开，无法判断里面的视频是真的被删除，还是只是暂时不在：\n\n%1\n\n请先让这些位置可用，再执行清理。"), QStringLiteral("These locations cannot be opened right now, so there is no way to tell whether the videos inside were deleted or are just temporarily away:\n\n%1\n\nMake those locations available first, then clean up.")},
        {QStringLiteral("“%1”是本机蓝牙的入站端口，后面没有设备。\n\n请改选同一个设备名下的另一个蓝牙串口（标着“蓝牙串口 · 设备名”的那个）。"), QStringLiteral("\"%1\" is the local inbound Bluetooth port and has no device behind it.\n\nPick the other Bluetooth serial port with the same device name (the one labelled \"Bluetooth serial · device name\").")},
        {QStringLiteral("脚本热力图（XTPlayer 同款配色）：绿色最慢，依次黄、橙、红，深红最快；上下边缘即 100 % 与 0 %，点击可跳转"), QStringLiteral("Script heat map (XTPlayer palette): green is slowest, then yellow, orange, red and dark red fastest; the top and bottom edges are 100% and 0%, click to seek")},
        {QStringLiteral("<b>NekoBeat %1</b><br>多轴脚本律动播放器<br><br>“设置 › 轴限制”可保存多套全局行程比例配置。"), QStringLiteral("<b>NekoBeat %1</b><br>Multi-axis script player<br><br>\"Settings › Axis limits\" keeps several global travel-ratio profiles.")},
        {QStringLiteral("收藏夹只记录视频位置，不会复制或移动文件；视频被移走或删除后会显示为失效项，可以一键清理。当前共 %1 个收藏夹，%2 个失效引用。"), QStringLiteral("Collections only record where a video is; no file is copied or moved. A video that was moved or deleted shows up as a missing entry you can clean up in one click. Currently %1 collections and %2 missing references.")},
        {QStringLiteral("文件：%1\n路径：%2\n分辨率：%3\n时长：%4\n大小：%5\n容器：%6\n视频编码：%7\n音频编码：%8\n硬解：%9\n脚本：%10\n收藏夹：%11"), QStringLiteral("File: %1\nPath: %2\nResolution: %3\nDuration: %4\nSize: %5\nContainer: %6\nVideo codec: %7\nAudio codec: %8\nHW decode: %9\nScript: %10\nCollections: %11")},
        {QStringLiteral("没有检测到任何串口。请确认设备已插好、驱动已安装，然后点“重新扫描”；如果蓝牙设备已经配对却一直不出现在这里，说明它的蓝牙不是串口类型，本程序无法通过蓝牙连接它。"), QStringLiteral("No serial ports were detected. Check that the device is plugged in and its driver is installed, then click Rescan. If a paired Bluetooth device never shows up here, its Bluetooth is not the serial kind and this program cannot connect to it over Bluetooth.")},
        {QStringLiteral("下面的条目指向的文件已经不在了。挑出它们的新位置后，收藏夹、循环片段和标签都会一起跟过去。\n只会勾选证据充分的匹配（同大小、同修改时间或同时长），仅同名的需要你自己确认。"), QStringLiteral("The files these entries point at are gone. Pick their new locations and the collections, loop clips and tags all follow along.\nOnly matches with solid evidence (same size, same modified time or same duration) are ticked; a name-only match is left for you to confirm.")},
        {QStringLiteral("如果这个端口显示“被占用”，请关闭占用它的程序（串口助手、Arduino IDE、另一个播放器）后重试；如果显示“驱动异常”，请在设备管理器里重新安装 USB 串口驱动。"), QStringLiteral("If this port shows \"in use\", close the program holding it (serial monitor, Arduino IDE, another player) and retry; if it shows \"driver problem\", reinstall the USB serial driver in Device Manager.")},
        {QStringLiteral("只作用于播放/暂停这个动作（控制条按钮、Space、画面右键）：\n按下播放时设备按上面的速度档位缓动进入脚本；\n按下暂停时设备滑行到当前动作段的终点再停（不超过 0.6 秒）。"), QStringLiteral("Applies only to the play/pause action (control-bar button, Space, right-click on the picture):\nplaying eases into the script at the speed set above;\npausing glides to the end of the current motion segment and stops there (at most 0.6 s).")},
        {QStringLiteral("选一个端口。“状态”会说明它能不能用：被其他程序占用时可以点“强制释放”先放开本程序仍持有的句柄，再重试。\n蓝牙设备在 Windows 里配对后会出现在这里，并标出配对时的设备名（例如“蓝牙串口 · SR6-BT”）；只列出真正能连的那个蓝牙口，系统多余的“入站端口”不会显示。"), QStringLiteral("Pick a port. The Status column says whether it works: when another program holds it, click \"Force release\" to let go of the handle this program still owns, then retry.\nA paired Bluetooth device appears here with the name it was paired under (for example \"Bluetooth serial · SR6-BT\"); only the connectable Bluetooth port is listed, the redundant inbound one is hidden.")},
        {QStringLiteral("这是一个蓝牙串口。请确认：\n· 设备已开机，并且在电脑附近；\n· Windows“蓝牙和其他设备”里设备显示为已连接（未连接就点一下它重新连）；\n· 没有其它程序（串口助手、另一个播放器）占着这个蓝牙串口——蓝牙串口同一时间只能被一个程序打开。\n\n如果刚给设备上电，等待两秒再点一次连接通常就好了。"), QStringLiteral("This is a Bluetooth serial port. Please check:\n· the device is powered on and near the computer;\n· Windows shows it as connected under \"Bluetooth & other devices\" (if not, click it to reconnect);\n· no other program (serial monitor, another player) holds this Bluetooth port - only one program can open it at a time.\n\nIf you just powered the device on, waiting two seconds and connecting again usually works.")},
        {QStringLiteral("设备的安全移动一共分三类，本开关只控制第一类：<br><br><b>① 需要缓动（受本开关控制）</b><br>进度条跳转（播放中或暂停中）、媒体库连播切换视频、循环列表切换片段与循环回跳、从停止状态打开新视频、设备刚连接时接管联动。<br><br><b>② 固定时长（不受本开关影响）</b><br>播放结束回中约 1 秒、复位约 1.2 秒、轴限制拖动预览约 0.7 秒。<br><br><b>③ 播放 / 暂停（由上面的「播放 / 暂停也使用缓动」开关控制）</b><br>开启时，按下播放会按同样的斜坡缓动进入脚本；按下暂停时设备滑行到当前动作段的终点再停下（滑行时长按上面的速度档位计算，限制在 0.12–0.6 秒），不会停在半程，也不会反向。<br>关闭时：恢复播放直接到位，暂停立即发送 DSTOP。<br>无论开关如何，切换视频、终止、断开设备、退出程序、复位与急停都会立即停止。<br><br>关闭本开关后，①类场景会让设备按脚本时间尽快到达目标位置。"), QStringLiteral("Safe device movement falls into three groups, and this switch owns only the first:<br><br><b>① Needs easing (controlled by this switch)</b><br>Seeking on the progress bar (playing or paused), switching videos during auto-next, switching loop clips and the loop rewind, opening a new video from a stopped state, and taking over sync when a device has just connected.<br><br><b>② Fixed duration (not affected by this switch)</b><br>Returning to centre at the end of playback takes about 1 s, reset about 1.2 s, and the axis-limit drag preview about 0.7 s.<br><br><b>③ Play / pause (controlled by the \"Ease play / pause too\" switch above)</b><br>When on, pressing play eases into the script along the same ramp; pressing pause glides to the end of the current motion segment and stops (the glide time comes from the speed setting above, clamped to 0.12–0.6 s) without stopping half-way or reversing.<br>When off: resuming jumps straight into place and pausing sends DSTOP immediately.<br>Either way, switching videos, stopping, disconnecting, quitting, resetting and the panic stop always stop immediately.<br><br>With this switch off, the group-① cases bring the device to its target as fast as the script clock allows.")},
    };
    return table;
}

} // namespace

const QString& lookupEnglish(const QString& source)
{
    static const QString kMissing;
    const auto it = englishTable().constFind(source);
    return it == englishTable().constEnd() ? kMissing : it.value();
}

} // namespace Loc
